#!/bin/bash

ourName=`basename "$0"`

# Step 1: rebuild
echo ${ourName}: rebuilding
time make

# Step 2: test ISSING requests
for noun in അവർ അവൻ അത് അവൾ ഇത് പരുക്കൻ കര ഇവ പണ ിക്കാർ
do
	time gdb ./reqHandlerTest-debug-dynamic <<END
set args $noun
run
END
done
