#!/bin/bash

for inpFile in ./inputs/* # Loop through each input
do
	./malStrLen-debug $inpFile
	echo --------------------------------------------------------------------------------------------------------
done
