# Directory where our headers are stored
incDir=./hpp

# Compilation options that are common to all builds
compOpts=-I$(incDir)

# Directory where C++ files are stored
cppDir=./cpp

# Compiler to use
compiler=g++-9

# Directory where object files are stored
objDir=./obj
